# Generated by Django 4.1 on 2023-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_course_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.CharField(max_length=200),
        ),
    ]
